[pytest]
pythonpath = .
addopts = --ignore-glob=*sync-conflict* -p no:cacheprovider
filterwarnings =
    error
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated, use anyio\.from_thread\.BlockingPortal instead\.:DeprecationWarning:starlette\.testclient
